#!/usr/bin/env bash
clear
echo -e "\e[1;91m$(cat <<'ART'
'''''''''.             .'''''''''    '''''''''    .''''''''.       '''''''''.   .''''''''''''''',,,,,,,.   .,,,,,,,,,,,,,,,,,,,,,,.   .,,,.,,,,,,,,,,,,,,,,,,.   .,,,,,,,,,,,,,,,,,,,,,,.   .,,,,,,,,,,,.',,,,,,,,,.   .,,,,,,,,,,,,,,,,,.,,,,'            
                   ;xxxxxxxxd              xxxxxxxxx:   :xxxxxxxxx    xxxxxxxxx:      .xxxxxxxxx'   oxxxxxxxxxxxxxxxxxxxxxx,   lxxxxxxxxxxxxxxxxxxxxxx:   :xxx'xxxxxxxxxxxxxxxxxxc   ;xxxxxxxxxxxxxxxxxxxxxxo   'xxxxxxxxxxxd,::dxxxxxxx   .xxxxxxxxxxxxxxxxx;lxxxx.           
                   lllddddol.             ;oooxxxxxx    xxxxxxxxxc   ,xxxxxolll.      'lodxxxxxx.   xxxxxxxxxxxkkkkkkkkkkkk'   oxxxxxxxxxxkkkkkkkkkkkk:   ;xxx'xxxxxxxxxxxxxxxxxxd   .xxxxxdoollxxxdoolcxxxxx.   xxxxxxxxxxxkkkd'xkkkkkx;   :kkkkkodxxxxxxxxxd.xkkkd           
                  oooooooooolll       ,ccclll,;xxxx:   ;xxxxxolcc.   dxxxxxxooolll.   cllccldddc   .xxxxxxxxxc                 dxxxxxxxxx.                ,xxx;oxxxx'   lxxxxxxxxx    xxxxx,    xxx;    lxxxx;   :xxxxxxxxx'                       .xxxxxxxxxc                 
                 ;xxxxxxxxxxxx;       xxxxxxx:cxxxx.   xxxxxxxxxd   .xxxxxxxxxxxxx    xxxxxxxxxl   .cccclxxxx;                 xxxkkkkxxx                 .:ll.;xxxx;   :xxxxxxxxx.   dxxxxl''''';,..'''cxxxxo   .xxxxxxxxxc                        lxxxxxxxxx.                
                .xxxxxxxxxxxxd       'ccllllc.,ccc;   ,xxxxxxxxx;   cxxxxxxxxxxxxl   'xxxxxxxxx,   :xxxxxxxxx'                 xxolloollc                 .xxxd,:cldc   ,xxxxxxoll'   cxxxxxxx'.     .;xxxxxxx.   oxxxxxxxxx.                       .xxxxxxxxxo                
                lxxxxxxxxxxxxxdddddddxxxxxxxxxxxxx.   oxxxxxxxxx    xxxxxxxxxxxxxxdddxxxxxxxxxx.   oxxxxxxxxxxdddddl'dddddd    xxxxxxxxxd                 .xxxxxxxxxxdddxxxxlll.      'xxxxxxx.        xxxxxxx:   ,xxxxxxxxxxxxxxxxl:xxxxx:          :xxxxxxxxx,               
               ;xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxl   .xxxxxxxxxc   'xxxxxxxxxc...cxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxo,xxxxxx    doxxxxxxxx                  xxxxxxxxxxxxxxxxxdddc;;;   .xxxxxxx,  looc  cxxxxxxd    xxxxxxxxxxxxxxxxx'xxxxxx           xxxxxxxxxd               
              .xxxxxxxxxddxddxxxxxxoxxdxxxxxxxxxx.   oxxxxxxxxx.   lxxxxxxxxx.   lxxxxxxxxxxxxl   .xxxxxxxxxdodddddlldddddl   .loxxxxxxxd                  xxxxxxxxxxoddoxxxxxxxxxx.   dxxxxxxdooxxxxoodxxxxxxx.   cxxxxxxxxxddddxdl.oddxxd'          ;xxxxxxxxx:              
              ;oolxxxxxx.   dxxxxxl   'xxxxxxxxxo   .xxxxxxxxxo   .xxxxxxxxxd    xxxxxxxxxxxxx;   ,xxxxxxxxxc                 .xxxxxxxxxd                  xxxxxxxxxx.   dxxxxxxxxx.   cxxxxxxxxxxkkkxxxxxxxxxxc   .xxxxxxxxxo                         dxxxxxxxxx.             
             'xxo.xxxxx;   ;xxxxxx.   oxxxxxxxxx'   lxxxxxxxxx,   'llolccccc,    ..':coddc'xxx.   cxxxxxxxxx,                 .xxxxxxxxxo                  dxd,lllllc.   lxxxxxxxxx;   ,xxxxxxxxxd...,xxxxxxxxxx    xxxxxxxxxx.                        .,:llllccc;             
            .xxx..cccc;    oddxxd:   'xxxxxxxxxo   .xxxxxxxxxx    dxxxxxxxxx.      .xxxxxx.xxx    cooodxxxxx'                 'xxxxxxxxxo                  oxo,xxxxxx,   'clolcoxxxl   .xxxxxxxxxx    cllllccccc.   :xxxxxxxxxc                         cdxxxxxxxx;            
            lxx:;xxxxx'     ......   dxxxxxxxxx'   :xxxdxxxxxc   .xxxxxxxxxd       ,xxxxxo,xxd   .dddl'xxxxxxxxxxxxoccc.lx;   ,xxxxxxxxxxxxxxxxxxddxxxx.   lxx'xxxxxx:   'xxxxxxxxxd    xxxxxxxxxx.   cxxxxxxxdd:   .xxxxxxxxxx                         .xxxxxxxxxx.           
           'xxx;;cccc;        ..... ,xxxxxxxxxo    xxxo;xxxxx.   cxxxoxxxxx:       lxxxxx;lxx:   'xxxx'xxxxxxxxxxxo.ooodxx'   ;xxxxxxxxxxxxxxxxxxo;xxxx.   cxl,xxxxxxl   .xxxxxxxxxx    lxxxxxxxxx:   'xxxxxxxxxx    oxxxxxxxxx;                         lxxxxxxxxxc           
           xkkkkkkkkd.          ....dkkkkkkkkx,   ;kkk,lkkkkd    xkkd.kkkkk.       xkkkkx'xkk'   :kkkx.xkkkkkkkkkkl;kkkkkx.   ;kkkxl''',dkkkkkkkkd.xkkx.   ;l,kkkkkkkd    xkkodkkkkx.   ;kkkkdokkkd    dkkkkkkkkk'   ,xkkkkkkkkd                         .dkkkkkkkkk.          
            .........             .. ..........    .... .....     ... .....        ...... ...     .... ...................     ......   .......... ....     .........     ..........     .........     ..........    ..........                           .........            
              .........                .........     .........     .........        ...... ...     .......................     .................. .....    ..........    .........      .........     ..........    ..........                       .  .........              
                ........                 .........    ..........    ..........       ..........    .....................        ................. .....    .........     .........     ........      .........      ........                             ......                
                   ........               .......       .........    ..........        .........    .......................    .................. ....     ......       ..........    .........     .........    ..........                         .........                  
                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                     
ART
)\e[0m"
